[project]
name = "bundesliga-fantasy-manager-assistant"
version = "0.1.0"
description = "Analyzes Bundesliga player data, in order to make recommendations to someone using the Bundesliga Fantasy Manager application."
readme = "README.md"
authors = [
    { name = "Jim Tyhurst", email = "jim@tyhurst.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
bundesliga-fantasy-manager-assistant = "bundesliga_fantasy_manager_assistant:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
